<div class='tabs'>
    {{include file='_admin/form_errors.phtml'/}}

    <dl class="required field">
      <dt><label for="id_node">id_node:</label></dt>
      <dd>{{input name='id_node' type='text' title='id_node'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="id_specs">id_specs:</label></dt>
      <dd>{{input name='id_specs' type='text' title='id_specs'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="title_specs">title_specs:</label></dt>
      <dd>{{input name='title_specs' type='text' title='title_specs'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="value_specs">value_specs:</label></dt>
      <dd>{{input name='value_specs' type='text' title='value_specs'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="branch">branch:</label></dt>
      <dd>{{input name='branch' type='text' title='branch'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="id_root">id_root:</label></dt>
      <dd>{{input name='id_root' type='text' title='id_root'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="id_parent">id_parent:</label></dt>
      <dd>{{input name='id_parent' type='text' title='id_parent'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="level">level:</label></dt>
      <dd>{{input name='level' type='text' title='level'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="alias">alias:</label></dt>
      <dd>{{input name='alias' type='text' title='alias'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="path">path:</label>
      <dd>{{input name='path' type='text' title='path'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="is_uiuser">is_for_ui:</label>
      <dd>{{input name='is_uiuser' type='text' title='is_uiuser'/}}</dd>
    </dl>

    {{include file='_admin/form_buttons.phtml'/}}
</div>
