<html>
<head>
    <title>{$#title} :: Limb3 SHOP example</title>
    <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
    <link rel=stylesheet type="text/css" href="/styles/main.css"/>
</head>
<body>

<div id="header">
    <div class="center">
        <table>
            <tr>
                <td>
                    <img src="/images/logo.limb.gif" width='384' height='46' alt='logo.limb' id='logo'/>
                </td>
                <td>
                    {{include file='_widgets/found.phtml' base_path='/' title="Параметры поиска" /}}
                </td>
                <td>
                    {{include file="user/include/profile_box.phtml" user="$#toolkit.user"/}}
                </td>
            </tr>
        </table>

        <div id="limb_links">
            <a href="http://limb-project.com">limb-project.com</a>&nbsp;|&nbsp;11
            <a href="http://bits.limb-project.com">bits.limb-project.com</a>
        </div>
    </div>

    <div>
        <a href="/">Main</a>
        <a href="/product/">Products</a>
        <a href="/cart/">Корзина</a>
        <a href="/tree_cart/">Корзина</a>
        <a href="/treecart/">Корзина</a>
        <a href="/admin/">Админка</a>
        <a href="/">*Главная страница</a>
        <a href="/">*Корзина</a>
        <a href="/treecategory/">*Страница категори</a>
        <a href="/info/">*Страница Одного Товара</a>

        <? if ($this->toolkit->getUser()->is_logged_in) { ?>
            <a href="/user/orders/">Заказы</a>
        <? } ?>
    </div>

</div>

<?php

$sorted = lmbTreeHelper :: sort($this->childrens, array('id' => 'ASC'));
$treeLeft = new lmbTreeNestedCollection($sorted);
$treeLeft->setChildrenField('preloaded_children');
$treeLeft->rewind();
?>


{{tree using="{$treeLeft}" as="$item" kids_prop="preloaded_children" counter="$counter" prefix=""}}
<ul >
    {{tree:node}}
    <li>
        {$counter})
        <a href="{{route_url params="action:branch"/}}/?id={$item.identifier}">{$item.id}::{$item.path}</a>
        {{tree:nextlevel/}}
    </li>
    {{/tree:node}}
</ul>
{{/tree}}

{{list using="$#items_child_nodes"}}
<ul>
    {{list:item}}
    <li>
        <a href="/?id={$item.id}">**{$item.id}**</a>::({$item.path})::
        <a href="/?id={$item.identifier}">**{$item.id}**()</a>
    </li>
    {{/list:item}}
</ul>
{{/list}}


</body>
</html>