{{include file='_admin/form_errors.phtml'/}}

<dl class="required field">
  <dt><label for="title">Title<span class="star">*</span> :</label></dt>
  <dd>{{input name='title' type='text' title='Title'/}}</dd>
</dl>

<dl class="required field">
  <dt><label for="name">Descr<span class="star">*</span> :</label></dt>
  <dd>{{input name='descr' type='text' title='Descr'/}}</dd>
</dl>

<dl class="required field">
  <dt><label for="email">identifier<span class="star">*</span> :</label></dt>
  <dd>{{input name='identifier' type='text' title='identifier'/}}</dd>
</dl>
