{{wrap with="front_page_layout.phtml" in="content_zone"}}
<h1>Node #{$this->id}</h1>
<p><a href="..">назад</a></p>

<div style="display: flex;">
<div style="align-self: flex-start; width: 300px">

    <br>
    <h2>Item tree ... </h2>

    <?php
    lmb_require('limb/tree/src/lmbTreeNestedCollection.class.php');
    lmb_require('limb/tree/src/lmbTreeHelper.class.php');

    lmb_require('limb/tree/src/lmbTreeDecorator.class.php');
    lmb_require('limb/tree/src/lmbMPTree.class.php');

/*
    foreach ($tst_arr as $key => $document) {
        //if(($document->getParentId() == $parent_id) and ($document->getIdentifier() == $identifier))
        //    return $document;
        if (
            ($document->getParentId() == $parent_id)
            and
            ($document->getIdentifier() == $identifier)
        ) {
            lmb_var_debug($document);
            echo('<br><br>');
            //lmb_var_debug( $tree1->getChildrenAll($document));
        }
    }
*/
    echo '<br>';

    $sorted = lmbTreeHelper :: sort($this->childrens, array('id' => 'ASC'));
    $tree_tst = new lmbTreeNestedCollection($sorted);
    $tree_tst->setChildrenField('preloaded_children');
    $tree_tst->rewind();
    //lmb_var_debug(sizeof($tree_tst));
    //style="display: list-item;
    ?>

    {{tree using="{$tree_tst}" as="$item" kids_prop="preloaded_children" counter="$counter" prefix=""}}
    <ul >
        {{tree:node}}
        <li>
            {$counter}) <a href="{$item.id}">{$item.id} : {$item.identifier}</a> {{tree:nextlevel/}}
        </li>
        {{/tree:node}}
        {{tree:empty}}
        tree_array is empty
        {{/tree:empty}}
    </ul>
    {{/tree}}

    <br> see you ... <br>

</div>

<div style="lign-self: flex-end; margin: 5px 5px; font-size: 18;">
    <table border="1" style="font-size: 18px; ali">
        <tr>
            <th>#</th>
            <th>id</th>
            <th>id_sys_tree</th>
            <th>id_pr</th>
            <th>value_pr</th>
            <th>is_branch</th>
        </tr>

        <tr>
            <th colspan="6">my_children</th>
        </tr>
        {{list using='$this->childrens' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>{$item.id}</td>
            <td>{$item.parent_id}</td>
            <td>{$item.level}</td>
            <td>{$item.identifier}</td>
            <td>{$item.path}</td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">...</td>
        </tr>
        {{/list:empty}}
        {{/list}}

        <tr>
            <th colspan="6">my_specifications</th>
        </tr>
        {{list using='$this->specifications' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>({$item.id})</td>
            <td>({$item.id_sys_tree})</td>
            <td>({$item.id_pr})</td>
            <td>({$item.value_pr})</td>
            <td>({$item.is_branch})</td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">пусто :-(</td>
        </tr>
        {{/list:empty}}
        {{/list}}

        <tr>
            <th colspan="6">childrens_specifications</th>
        </tr>
        {{list using='$this->child_specs' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>({$item.id})</td>
            <td>
                <?php
                    if($item['is_branch']==0)
                    {
                        echo '<a href="../item/'.$item['id_sys_tree'].'">';
                        echo '<img src="/shared/images/icons/application_view_detail.png" alt="detail" /></a>';
                    }
                    else
                        echo '&nbsp;';
                ?>

                ({$item.id_sys_tree})
                <?php
                    if($item['is_branch']==0)
                    {
                        echo '<a href="/toCart/'.$item['id_sys_tree'].'">';
                        echo '<img src="/shared/images/icons/cart_add.png" alt="2cart" /></a>';
                    }
                ?>
            </td>
            <td>({$item.id_pr})</td>
            <td>({$item.value_pr})</td>
            <td>({$item.is_branch}): {$this->pref[$item['id_pr']]}</td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">пусто :-(</td>
        </tr>
        {{/list:empty}}
        {{/list}}

        <tr>
            <th colspan="6">legacy_specifications</th>
        </tr>
        {{list using='$this->legacy_specs' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>({$item.id})</td>
            <td>({$item.id_sys_tree})</td>
            <td>({$item.id_pr})</td>
            <td>({$item.value_pr})</td>
            <td>
                <p <?php if (in_array($item['id'], $this->arr_notAdded)) echo 'style="text-transform:uppercase;"'; ?> >
                    ({$item.is_branch}): {$this->pref[$item['id_pr']]}
                </p>
            </td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">пусто :-(</td>
        </tr>
        {{/list:empty}}
        {{/list}}

        <tr>
            <th colspan="6">preference(specifications)</th>
        </tr>
        {{list using='$this->specs' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>({$item.id})</td>
            <td>()</td>
            <td>()</td>
            <td>({$item.title})</td>
            <td>({$item.importance}): {$this->pref[$item['id']]}
                <?php /* echo $this->pref[$item['id']];*/ ?>
            </td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">пусто :-(</td>
        </tr>
        {{/list:empty}}
        {{/list}}

    </table>
</div>

</div>


{{/wrap}}