{{include file='_admin/form_errors.phtml'/}}

<dl class="required field">
  <dt><label for="title">Название:</label></dt>
  <dd>{{input name='title' type='text' title='Название'/}}</dd>
</dl>

<dl class="required field">
    <dt><label for="importance">importance:</label>
    <dd>
        {{js_checkbox
            name='importance'
            id='importance'
            checked_value='importance'
        /}}
    </dd>
</dl>


{{include file='_admin/form_buttons.phtml'/}}