{{wrap with="admin_page_layout.phtml" in="content_zone"}}

{{include file="_admin/selectors.phtml"/}}
{{include file="_admin_object/actions.phtml"/}}

{{into slot="content_zone"}}
<div id="header">
    <h1>
        full MENU: admin_tree_full display
        <?php
        echo sizeof($this->items);
        //lmb_var_debug($this->items);
        ?>
    </h1>

    <div class="header_actions">
        <a href='{{route_url params="action:create"/}}'
           title="Create category or product" class='thickbox'>
            <img src='/shared/images/icons/page_white_add.png'/> Create -tree_full-
        </a>

        <a href='{{route_url params="action:treefull"/}}'
           title="View for user design" class='thickbox'>
            <!-- <img src='/shared/images/icons/page_white_add.png'/> --> Пользовательский вид
        </a>
    </div>
</div>

<div id="body">
    <div class="list">
        {{list using='{$#items}' parity='{$parity}'}}
        {{include file="_admin_object/actions.phtml"/}}
        ( items )
        <table>
            <tr>
                <th>Actions</th>
                <th>#ID</th>
                <th>node_id</th>
                <th>root_id</th>
                <th>parent_id</th>
                <th>priority</th>
                <th>level</th>
                <th>path</th>
                <th>children</th>
                <th>identifier</th>
                <th>is_branch</th>
            </tr>
            {{list:item}}
            <tr class='{$parity}'>
                <td class='actions'>
                    {{apply template="object_action_edit" item="{$item}" icon="page_white_edit" /}}
                    {{apply template="object_action_delete" item="{$item}" icon="page_white_delete" /}}
                </td>

                <td>#{$item.id}</td>
                <td>#{$item.node_id}#</td>
                <td>{$item.root_id}</td>
                <td>{$item.parent_id}</td>
                <td>{$item.priority}</td>
                <td>{$item.level}</td>
                <td>{$item.path}</td>
                <td>{$item.children}</td>
                <td>
                    {$item.identifier} /
                    <?php
                    //lmb_var_debug($item->gettreeitem());
                    //lmb_var_debug($item->gettreeitem()->getIds());
                    //lmb_var_debug($item->gettreeitem()->getArray());
                    //lmb_var_debug($item->gettreefull());
                    ?>
                </td>
                <td>{$item.is_branch}</td>

            </tr>
            {{/list:item}}
            {{list:empty}}
            <div class="empty_list">Empty items</div>
            {{/list:empty}}
        </table>
        {{/list}}
    </div>


    <div class="list">
        {{list using='{$#tree_items}' parity='{$parity}'}}
        {{include file="_admin_object/actions.phtml"/}}
        ( tree_items )
        <table>
            <tr>
                <th>Actions</th>
                <th>#ID</th>
                <th>node_id</th>
                <th>Характеристика</th>
                <th>Значение_Свойства</th>
                <th>is_branch</th>
            </tr>
            {{list:item}}
            <tr class='{$parity}'>
                <td class='actions'>
                    {{apply template="object_action_edit" item="{$item}" icon="page_white_edit" /}}
                    {{apply template="object_action_delete" item="{$item}" icon="page_white_delete" /}}
                </td>
                <td>#{$item.id}</td>
                <td>#{$item.node_id}#</td>
                <td>{$item->gettreeattribute()->getTitle()}</td>
                <td>{$item.attr_value}</td>
                <td>{$item.is_branch}</td>
            </tr>
            {{/list:item}}
            {{list:empty}}
            <div class="empty_list">Empty tree_items</div>
            {{/list:empty}}
        </table>
        {{/list}}
    </div>

    <?php
    //@todo this fragment to ShopTools
    $arr = lmbCollection::toFlatArray($this->tree_items);
    //lmb_var_debug($arr);
    $tmp = array();
    foreach($arr as $key => $val) {
        //$tmp[$key][$val[$key]][]= array('id'=>$val['id'], 'title'=>$val['title']);
        $tmp[ $val['node_id']][] = array(
            'id' => $val['id'],
            'node_id' => $val['node_id'],
                'attr_id' => $val['attr_id'],
        'attr_value' => $val['attr_value'],
        'is_branch' => $val['is_branch']) ;
        //echo '<br>'.$key;
    }
    //lmb_var_debug($tmp);
    $this->arr_tovar = $tmp;
    ?>

    <div class="list">
        {{list using='{$#arr_tovar}' parity='{$parity}'}}
        {{include file="_admin_object/actions.phtml"/}}
        ( arr_tovar )
        <table>
            <tr>
                <th>#ID</th>
                <th>Заголовок</th>
                <th>Описание</th>
                <th>Идентификатор</th>

                <th>Дата добавления</th>
                <th>Дата обновления</th>

                <th>Цена</th>
            </tr>
            {{list:item}}
            <tr class='{$parity}'>

                <?php
                $node_id = $item[0]['node_id'];
                $node['id'] = $node_id
                ?>

                <td class='actions'>
                    {{apply template="object_action_edit" item="$node" icon="page_white_edit" /}}#
                    {$item[0].node_id}#{$item[0].is_branch}::
                    <!-- <img src='/shared/images/icons/application_view_detail.png'/> -->
                </td>

                <?php
                //@todo this fragment to ShopTools
                $arr_tovar_attr = array_reverse($item);
                ?>

                {{list using='{$arr_tovar_attr}' as='$tovar'}}
                    {{list:item}}
                    <td>
                        {$tovar.attr_value}
                    </td>
                    {{/list:item}}
                {{/list}}
            </tr>
            {{/list:item}}
            {{list:empty}}
            <div class="empty_list">Empty items</div>
            {{/list:empty}}
        </table>
        {{/list}}
    </div>

</div>
{{/into}}
{{/wrap}}
