{{wrap with="admin_page_layout.phtml"}}

  {{include file="_admin/selectors.phtml"/}}
  {{include file="_admin_object/actions.phtml"/}}

  {{into slot="content_zone"}}
    <div id="header">
      <h1>Preference</h1>

      <div class="header_actions">
        <a href='{{route_url params="action:create"/}}'
           title="Create preference" class='thickbox'>
            <img src='/shared/images/icons/page_white_add.png'/> Create preference
        </a>
      </div>
    </div>

    <div id="body">
      {{list using='{$#items}' parity='{$parity}'}}
      {{include file="_admin_object/actions.phtml"/}}
      <div class="list">

        <table>
          <tr>
            <th>{{apply template="selectors_toggler"/}}</th>
            <th>#ID</th>
            <th width='20%'>Title</th>
            <th width='40%'>is_published_for_user</th>
            <th>Actions</th>
          </tr>
          {{list:item}}
            <tr class='{$parity}'>
              <td>{{apply template="selector" value="{$item.id}"/}}</td>
              <td>#{$item.id}</td>
              <td>{$item.title}</td>
              <td>
                  {{form name='my_form'}}
                  <label for='importance'>({$item.importance}):</label>
                  {{js_checkbox name='importance' id='importance'
                    checked_value='$item.importance' /}}
                  <?php
                  echo ((!$item->getImportance()==0) ? 'true' : 'FALSE');
                  //echo ' :'.lmb_translit_russian( $item->getTitle() );
                  //echo ' :'. str_replace(' ', '_', $item->getTitle() );
                  echo ' :'. lmb_translit_russian(str_replace(' ', '_', $item->getTitle() ));
                  //echo ' :'.lmb_i18n(str_replace(' ', '_', $item->getTitle()));
                  ?>

                  {{/form}}
              </td>
              <td class='actions'>
                {{apply template="object_action_edit"  item="{$item}" icon="page_white_edit" /}}
                {{apply template="object_action_delete" item="{$item}" icon="page_white_delete" /}}
              </td>
            </tr>
          {{/list:item}}
          {{list:empty}}
            <div class="empty_list">Empty</div>
          {{/list:empty}}
        </table>
      </div>
      {{/list}}
    </div>
  {{/into}}
{{/wrap}}