<div class='tabs'>

  <ul>
    <li id='properties'><a>Properties</a></li>
  </ul>

  <div id="tab_properties">

    <dl class="required field">
      <dt><label for="title">Название:</label></dt>
      <dd>{{input name='title' type='text' title='Название'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="identifier">identifier:</label>
      <dd>{{textarea name='identifier' title='ИД_Описание'/}}</dd>
    </dl>

    <dl class="required field">
      <dt><label for="descr">Описание:</label>
      <dd>{{textarea name='descr' title='Описание'/}}</dd>
    </dl>

  </div>

</div>