<? $this->title = ($this->title) ? $this->title : 'Main page '; ?>

{{wrap with="front_page_layout.phtml" into="content_zone"}}
<!-- content_begin -->
{{include file="_admin_object/actions.phtml"/}}

<div id="body" style="display: flex; padding: 6px">
    <div style="align-self: flex-start; width: 320px">
        <hr>
        <h4 style="background-color: #add8e6;">Список категорий</h4>
        <p style="background-color: lightgray; display: none;">items_child_nodes</p>
        {{list using='{$#items_child_nodes}' as='$item' counter='$my_counter' }}
        {{list:item}}

        <h5> <a href="/pagecategory/{$item.identifier}"> {$item->getTitle()} </a> </h5>
        {{/list:item}}
        {{/list}}
        <hr>
    </div>

    {{template name="info_tpl"}}
    <div style="margin: 2px; padding: 8px;">
        <h2>
            <?php
            $item_title = TreeItem :: getTitleByNodeId($item['node_id']);
            $item_uri = TreeItem :: getUriByNodeId($item['node_id']);
            echo '<a href="/pageitem/'.$item_uri.'">'.$item_title.'</a>';
            echo ' ';
            echo ($item->get('is_branch') == 0) ?
                '<a href="/tree_cart/add/'.$item->get('node_id').'">В корзину</a>':'';
            ?>
        </h2>

        <ul>
            <li>
            <?php
                $descr = TreeItem :: getAttrValueByNodeId($item['node_id'],TreeItem::ID_DESCR);
            ?>
            description:<br> {$descr|raw|nl2br}
            </li>
        </ul>
    </div>
    {{/template}}

    <div class="list" style="lign-self: flex-end; margin: 5px 6px;">

        {{list using="$#main_last"}}
        <table border="1">
            <tr>
                {{list:item}}
                <td>
                    <b>[Сортировка по дате: {$item.udate}]</b>
                    {{apply template="info_tpl" item="$item"/}}
                </td>
                {{list:glue step="3"}}</tr><tr>{{/list:glue}}
                {{/list:item}}
                {{list:fill upto='3' items_left='$items_left'}}
                <td colspan='{$items_left}'>&nbsp;</td>
                {{/list:fill}}
            </tr>
        </table>
        {{/list}}
    </div>
</div>
<!-- content_end -->
{{/wrap}}