<? $this->title = ($this->title)?$this->title:'Main page '; ?>

{{wrap with="front_page_layout.phtml" into="content_zone"}}
<!-- content_begin -->
{{include file="_admin_object/actions.phtml"/}}

<div id="body" style="display: flex; padding: 6px">


<div style="align-self: flex-start; width: 320px">

    <?php

    $sorted = lmbTreeHelper :: sort($this->childrens, array('id' => 'ASC'));
    //lmb_var_debug($sorted);
    $tree_tst = new lmbTreeNestedCollection($sorted);
    $tree_tst->setChildrenField('preloaded_children');
    $tree_tst->rewind();
    //$tree_tst=array();

    ?>
<div style="display: none;"> <!--   -->
    <hr>
    <h2>wood</h2>
    {{tree using="{$#wood}" as="$item" kids_prop="preloaded_children" counter="$counter" prefix=""}}
    <ul >
        {{tree:node}}
        <?php $title = TreeItem::getTitleByNodeId($item['node_id']); ?>
        {{if var="$title"}
        <li>
            {$counter})
            <a href="/pagecategory/{$item.uri}">:{$item.path}&nbsp;|&nbsp;{$item.udate} <?php if (is_numeric($item['udate'])) { ?> - {$item.udate|date:"Y-m-d G:i:s"} <?php } ?> </a>
            {{tree:nextlevel/}}
        </li>
        {{/if}}
        {{/tree:node}}
    </ul>
    {{/tree}}
</div>
<div id="tree_tst">
    <hr>
    {{tree using="{$tree_tst}" as="$item" kids_prop="preloaded_children" counter="$counter" prefix=""}}
    <ul >
        {{tree:node}}
        <?php $title = TreeItem::getTitleByNodeId($item['node_id']); ?>
        <li>
            <a href="/pagecategory/{$item.identifier}">
                <?php echo $title; ?>
            </a>
            {{tree:nextlevel/}}
        </li>
        {{/tree:node}}
    </ul>
    {{/tree}}
</div>
    <div style="display: none;"> <!--  -->
    <hr>
    {{tree using="{$#wood}" as="$item" kids_prop="preloaded_children" counter="$counter" prefix=""}}
    <ul >
        {{tree:node}}
        <?php
        $title = TreeItem::getTitleByNodeId($item['node_id']);
        $uri = TreeItem::getUriByNodeId($item['node_id']);
        ?>
        <li>
            <a href="/pagecategory/{$uri}">
                <?php echo $title; ?>
            </a>
            {{tree:nextlevel/}}
        </li>
        {{/tree:node}}
    </ul>
    {{/tree}}
    </div>

</div>


<div class="list" style="lign-self: flex-end; margin: 5px 5px;">
<!-- -->

<div>


    <table border="1" style="display: none;">
        <tr>
            <td>id</td>
            <td>udate</td>
            <td>node_id</td>
            <td>is_branch</td>
            <td>path</td>
            <td>par_id</td>
            <td>uri</td>
            <td>level</td>
            <td>
                all
            </td>
        </tr>
        {{list using='{$#nodes_tree}'}}
        {{list:item}}
        <tr>
            <td>{$item.id}</td>
            <td>{$item.udate}</td>
            <td>{$item.node_id}</td>
            <td>{$item.is_branch}
                <?php
                echo ($item->get('is_branch')==0)?
                    '<a href="/tree_cart/add/'. $item->get('node_id'). '">+++</a>':
                    '---';
                ?>
            </td>
            <td>{$item.path}</td>
            <td>{$item.par_id}</td>
            <td>{$item.uri}</td>
            <td>{$item.level}</td>
            <td>
                {$item.id} / {$item.udate} / {$item.node_id} / {$item.is_branch} / {$item.path}  / {$item.par_id} / {$item.uri} / {$item.level}
            </td>
        </tr>
        {{/list:item}}
        {{/list}}
    </table>


</div>

{{list using='{$#arr_tovar}' parity='{$parity}' key='{$key}' }}
<div class="list" style="display: none;">
    <table>
        <tr>
            <th>#ID</th>
            <th>Заголовок</th>
            <th>Описание</th>
            <th>Идентификатор</th>

            <th>Дата добавления</th>
            <th>Дата обновления</th>

            <th>Цена</th>
        </tr>
        {{list:item}}
        <tr class='{$parity}'>
            <td>
                #{$item.id}({$key})
                <a href="/tree_cart/add/{$key}">+++</a>
            </td>

            <?php
            //@todo this fragment to ShopTools
            $arr_tovar_attr = array_reverse($item);
            ?>

            {{list using='{$arr_tovar_attr}' as='$tovar'}}
            {{list:item}}
            <td>
                {$tovar.attr_value}
            </td>
            {{/list:item}}
            {{/list}}

        </tr>
        {{/list:item}}
        {{list:empty}}
        <div class="empty_list">Empty items</div>
        {{/list:empty}}
    </table>
</div>
{{/list}}

<!-- -->
    <table>
        <tr>
            <th colspan="6"></th>
        </tr>

        {{tree using="{$tree_tst}"
            as="$item"
            kids_prop="preloaded_children"
            counter="$counter"
            prefix="1"}}

            {{tree:node}}
            <tr>
                <td colspan="6">
                    <?php $title = TreeItem :: getTitleByNodeId($item['node_id']); ?>

                    {{if var="{$item['level']}"}}

                    <?php
                    $isProduct = (TreeItem :: getIsBranchByNodeId($item['node_id'])==0);
                    $uri = TreeItem::getUriByNodeId($item['node_id']);
                    if($isProduct)
                    {
                        echo '<a href="/tree_cart/add/'. $item['node_id']. '"><img src="/shared/images/icons/cart_add.png" alt="2cart" /></a>';
                        $price = TreeItem::getPriceByNodeId($item['node_id']);
                        echo ($price)? ' Цена: '. $price. ' y.e.': '';
                    }

                    ?>

                    <h<?php echo $item['level']+1; ?>>
                        {$prefix}.{$counter} ) <a href="./{$uri}">{$title}</a>
                    </h<?php echo $item['level']+1; ?>>

                    <?php
                        $description = TreeItem::getDescriptionByNodeId($item['node_id']);
                        if($description) {
                    ?>
                        <p>Описание:<br> {$description|raw|nl2br}</p>
                    <?php
                        }
                    ?>

                    {{/if}}

                    {{tree:nextlevel prefix="$new_prefix"}}
                        <?php $new_prefix = $prefix . "." . $counter; $this->ind = $this->i+1;?>
                    {{/tree:nextlevel}}
                </td>
            </tr>
            {{/tree:node}}
        {{/tree}}
    </table>

    <table border="1" style="display: none;">
        <tr>
            <th>#</th>
            <th>id</th>
            <th>id_sys_tree</th>
            <th>id_pr</th>
            <th>value_pr</th>
            <th>is_branch</th>
        </tr>

        <tr>
            <th colspan="6">my_children</th>
        </tr>
        {{list using='$this->childrens' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>{$item.id}</td>
            <td>{$item.parent_id}</td>
            <td>{$item.level} lvl </td>
            <td>{$item.identifier}</td>
            <td>{$item.path}</td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">...</td>
        </tr>
        {{/list:empty}}
        {{/list}}

        <?php
//            echo '<img src="/shared/images/icons/application_view_detail.png" alt="detail" /></a>';
//            echo '<img src="/shared/images/icons/cart_add.png" alt="2cart" /></a>';
        ?>

    </table>
</div>

</div>
<!-- content_end -->
{{/wrap}}