<? $this->title = ($this->title) ? $this->title : 'Main page '; ?>

{{wrap with="front_page_layout.phtml" into="content_zone"}}
<!-- content_begin -->
{{include file="_admin_object/actions.phtml"/}}

<div id="body" style="display: flex; padding: 6px">

    <div style="align-self: flex-start; width: 320px;">

        <hr>
        <h4>"Узлы" дерева</h4>
        {{list using='{$#records}' parity='{$parity}'
         as="$item" counter="$counter" prefix=""}}
        <ul>
            {{list:item}}
            {{if var="{$item->getTitle()}"}}
            <li>
                <a href="/pageitem/{$item.identifier}">{$item->getTitle()}</a>
            </li>
            {{/if}}
            {{/list:item}}
        </ul>
        {{/list}}
    </div>

    <div class="list" style="lign-self: flex-end; margin: 5px 5px;">
        <!-- -->
        {{list using='{$#records}' parity='{$parity}'}}
        {{include file="_admin_object/actions.phtml"/}}
        <div class="list">

            <table>
                <tr>
                    <th>Характеристика</th>
                    <th>Значение_Свойства</th>
                </tr>
                {{list:item}}
                {{if var="{$item->getTitle()}"}}
                <tr class="odd">
                    <td colspan="2" style="text-align: center;">{$item->getTitle()}</td>
                    <!-- <td></td> -->
                </tr>
                {{/if}}
                {{list using='{$item->gettreeitem()}' parity='{$parity}' as='$it'}}
                        {{list:item}}
                        {{if var="{$it->gettreeattribute()->getIsPublished()}"}}
                        <tr>
                            <td>{$it->gettreeattribute()->getTitle()}</td>
                            <td>{$it.attr_value}</td>
                        </tr>
                        {{/if}}
                        {{/list:item}}
                {{/list}}
                {{/list:item}}
            </table>
        </div>
        {{/list}}
        <!-- -->
    </div>
</div>

<?php
//echo '<img src="/shared/images/icons/application_view_detail.png" alt="detail" /></a>';
//echo '<img src="/shared/images/icons/cart_add.png" alt="2cart" /></a>';
?>

<!-- content_end -->
{{/wrap}}