{{wrap with="admin_page_layout.phtml" in="content_zone"}}

{{include file="_admin/selectors.phtml"/}}
{{include file="_admin_object/actions.phtml"/}}

{{into slot="content_zone"}}
<div id="header">
    <h1>Node #{$this->id}</h1>

    <div class="header_actions">
        <a href='{{route_url params="action:create"/}}'
           title="Create preference" class='thickbox'>
            <img src='/shared/images/icons/page_white_add.png'/> Create preference
        </a>
    </div>

</div>

<div id="body" style="display: flex;">

<div style="align-self: flex-start; width: 320px">

    <?php
    lmb_require('limb/tree/src/lmbTreeNestedCollection.class.php');
    lmb_require('limb/tree/src/lmbTreeHelper.class.php');

    lmb_require('limb/tree/src/lmbTreeDecorator.class.php');
    lmb_require('limb/tree/src/lmbMPTree.class.php');


    $sorted = lmbTreeHelper :: sort($this->childrens, array('id' => 'ASC'));
    $tree_tst = new lmbTreeNestedCollection($sorted);
    $tree_tst->setChildrenField('preloaded_children');
    $tree_tst->rewind();
//    $uri = lmbToolkit::instance()->getRequest()->getUri();
//    lmb_var_debug($uri); new lmbUri()
    // self :: _getCallingClass();

    /*
        echo ($this->isTail)? 'is_tail':'is_not_tail';
        echo '<br>';
        echo ($this->isTailBranch)? 'is_tailBranch':'is_not_tailBranch';
        echo '<br>';
        echo ($this->isBranch)? 'is_Branch':'is_not_Branch';
        echo '<br>';
        echo (($this->isBranch)&&($this->isTailBranch)&&(!$this->isTail))? 'access_add_product':'not_access_add_tovar';
        echo '<br>';
    */
        $bl_mayBe = $this->isMayBe;
        $bl_access = ($this->isBranch)&&($this->isTailBranch)&&(!$this->isTail)&&($bl_mayBe);

        if($bl_access)
        {
            ?>
            <a href='{{route_url params="controller:admin_uitree,action:append"/}}/{$this->id}'
               title="Create product" class='thickbox'>
                <img src='/shared/images/icons/page_white_add.png'/> Добавить товар
            </a>
        <?php
        }
    ?>

    {{tree using="{$tree_tst}" as="$item" kids_prop="preloaded_children" counter="$counter" prefix=""}}
    <ul >
        {{tree:node}}
        <li>
            {$counter}) <a href="{$item.id}">{$item.id}</a>&nbsp;|&nbsp;
            <a href="{{route_url params="action:node"/}}/{$item.identifier}">{$item.identifier}</a>
            {{tree:nextlevel/}}
        </li>
        {{/tree:node}}
        {{tree:empty}}
        tree_array is empty
        {{/tree:empty}}
    </ul>
    {{/tree}}

    <p>May be append product this Node_tree: {$this->isTail}</p>
    <?php
    echo ($bl_mayBe)? 'yes_isMayBe':'no_isMayBe';
    echo '<br>';
    echo ($bl_access)? 'yes_access':'not_access';

    ?>

</div>


<div class="list" style="lign-self: flex-end; margin: 5px 5px;">

    <table border="1">
        <tr>
            <th>#</th>
            <th>id</th>
            <th>id_sys_tree</th>
            <th>id_pr</th>
            <th>value_pr</th>
            <th>is_branch</th>
        </tr>

        <tr>
            <th colspan="6">my_children</th>
        </tr>
        {{list using='$this->childrens' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>{$item.id}</td>
            <td>{$item.parent_id}</td>
            <td>{$item.level} lvl </td>
            <td>{$item.identifier}</td>
            <td>{$item.path}</td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">...</td>
        </tr>
        {{/list:empty}}
        {{/list}}

        <tr>
            <th colspan="6">my_specifications</th>
        </tr>
        {{list using='$this->specifications' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>({$item.id})</td>
            <td>({$item.id_sys_tree})</td>
            <td>({$item.id_pr})</td>
            <td>({$item.value_pr})</td>
            <td>({$item.is_branch})</td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">пусто :-(</td>
        </tr>
        {{/list:empty}}
        {{/list}}

        <tr>
            <th colspan="6">childrens_specifications</th>
        </tr>
        {{list using='$this->child_specs' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>({$item.id})</td>
            <td>
                <?php
                    if($item['is_branch']==0)
                    {
                        echo '<a href="../item/'.$item['id_sys_tree'].'">';
                        echo '<img src="/shared/images/icons/application_view_detail.png" alt="detail" /></a>';
                    }
                    else
                        echo '&nbsp;';
                ?>

                ({$item.id_sys_tree})
                <?php
                    if($item['is_branch']==0)
                    {
                        echo '<a href="/toCart/'.$item['id_sys_tree'].'">';
                        echo '<img src="/shared/images/icons/cart_add.png" alt="2cart" /></a>';
                    }
                ?>
            </td>
            <td>({$item.id_pr})</td>
            <td>({$item.value_pr})</td>
            <td>({$item.is_branch}): {$this->pref[$item['id_pr']]}</td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">пусто :-(</td>
        </tr>
        {{/list:empty}}
        {{/list}}

        <tr>
            <th colspan="6">legacy_specifications</th>
        </tr>
        {{list using='$this->legacy_specs' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>({$item.id})</td>
            <td>({$item.id_sys_tree})</td>
            <td>({$item.id_pr})</td>
            <td>({$item.value_pr})</td>
            <td>
                <p <?php if (in_array($item['id'], $this->arr_notAdded)) echo 'style="text-transform:uppercase;"'; ?> >
                    ({$item.is_branch}): {$this->pref[$item['id_pr']]}
                </p>
            </td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">пусто :-(</td>
        </tr>
        {{/list:empty}}
        {{/list}}

        <tr>
            <th colspan="6">preference(specifications)</th>
        </tr>
        {{list using='$this->specs' as='$item' counter='$my_counter' }}
        {{list:item}}
        <tr>
            <td>{$my_counter}</td>
            <td>({$item.id})</td>
            <td>()</td>
            <td>()</td>
            <td>({$item.title})</td>
            <td>({$item.importance}): {$this->pref[$item['id']]}
                <?php /* echo $this->pref[$item['id']];*/ ?>
            </td>
        </tr>
        {{/list:item}}
        {{list:empty}}
        <tr>
            <td colspan="6">пусто :-(</td>
        </tr>
        {{/list:empty}}
        {{/list}}

    </table>
</div>

</div>

{{/into}}
{{/wrap}}