{{wrap with="admin_page_layout.phtml"}}

{{include file="_admin/selectors.phtml"/}}
{{include file="_admin_object/actions.phtml"/}}

{{into slot="content_zone"}}
<div id="header">
    <h1>Preference - values - APPEND</h1>

    <div class="header_actions">
        <a href='{{route_url params="action:create"/}}'
           title="Create preference" class='thickbox'>
            <img src='/shared/images/icons/page_white_add.png'/> Create preference - value fot NODE!
        </a>

        <a href='{{route_url params="action:append_link_pref_and_node"/}}/1656'
           title="Append link preference-objoftree" class='thickbox'>
            <img src='/shared/images/icons/page_white_add.png'/> Append <b>link</b> preference-objoftree
        </a>

    </div>
</div>

<div id="body">
    <?php
    $criteria = null;
    $is_once = $this->id==0;

    if($is_once) {
        echo ' isNOL ';
        $criteria = new lmbSQLCriteria('id_sys_tree > '.$this->id);
    }
    else {
        echo ' not_NOL ';
        //$criteria = new lmbSQLCriteria('id_sys_tree = '.$this->id);
        $criteria = lmbSQLCriteria::equal('id_sys_tree', $this->id);
    }

    //lmb_var_debug($criteria);
    $this->items = lmbActiveRecord :: find('Objoftree', $criteria);
    //$this->items = lmbCollection::toFlatArray(lmbActiveRecord :: find('Objoftree', $criteria));
    echo sizeof($this->items);
    //return ;

    //lmb_var_debug($this->items);
    //$this->items->
    //lmb_var_debug(sizeof($this->items));
    //return ;
    ?>


    {{list using='{$#items}' parity='{$parity}'}}
    {{include file="_admin_object/actions.phtml"/}}
    <div class="list">

        <table>
            <tr>
                <th>{{apply template="selectors_toggler"/}}</th>
                <th>#ID</th>
                <th>id_sys_tree</th>
                <th>id_pr</th>
                <th>value_pr</th>
                <th>is_branch</th>

                <th>Actions</th>
            </tr>
            {{list:item}}
            <?php
                //if($item['id_sys_tree']==$this->id)
            //if(isset($this->id)) echo 'isset';
            //else echo 'not_set';

            {
            ?>
            <tr class='{$parity}'>
                <td>{{apply template="selector" value="{$item.id}"/}}</td>
                <td>#{$item.id}</td>
                <td>{$item.id_sys_tree} / {$item->getTree()->getIdentifier()}</td>
                <td>{$item.id_pr} / {$item->getPreference()->getTitle()}</td>
                <td>{$item.value_pr}</td>
                <td>
                    [ {$item.is_branch} ] ~
                    <?php
                    echo ((!$item->getIsBranch()==0) ? 'true-Ветка' : 'false-листок');
                    ?>
                </td>

                <td class='actions'>
                    {{apply template="object_action_edit"  item="{$item}" icon="page_white_edit" /}}
                    {{apply template="object_action_delete" item="{$item}" icon="page_white_delete" /}}
                </td>
            </tr>
                <?php
                }
            ?>
            {{/list:item}}
            {{list:empty}}
            <div class="empty_list">Empty</div>
            {{/list:empty}}
        </table>
    </div>
    {{/list}}
</div>
{{/into}}
{{/wrap}}